/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jumbo_JumboJni */

#ifndef _Included_org_jumbo_JumboJni
#define _Included_org_jumbo_JumboJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_jumbo_JumboJni
 * Method:    init
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_jumbo_JumboJni_init
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_jumbo_JumboJni
 * Method:    put
 * Signature: (I[B[B)V
 */
JNIEXPORT void JNICALL Java_org_jumbo_JumboJni_put
  (JNIEnv *, jobject, jint, jbyteArray, jbyteArray);

/*
 * Class:     org_jumbo_JumboJni
 * Method:    get
 * Signature: (I[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_jumbo_JumboJni_get
  (JNIEnv *, jobject, jint, jbyteArray);

/*
 * Class:     org_jumbo_JumboJni
 * Method:    del
 * Signature: (I[B)V
 */
JNIEXPORT void JNICALL Java_org_jumbo_JumboJni_del
  (JNIEnv *, jobject, jint, jbyteArray);

/*
 * Class:     org_jumbo_JumboJni
 * Method:    keys
 * Signature: (II)[[B
 */
JNIEXPORT jobjectArray JNICALL Java_org_jumbo_JumboJni_keys
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
