name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --tag jumbo:$(date +%s)
    - name: Publish image
      run: |
        echo ${GITHUB_TOKEN}
        echo ${GITHUB_TOKEN} | docker login docker.pkg.github.com -u Thoughtknot --password-stdin
        docker tag jumbo:$(date +%s) docker.pkg.github.com/Thoughtknot/jumbo/jumbo:$(date +%s)
        docker push docker.pkg.github.com/Thoughtknot/jumbo/jumbo:$(date +%s)
      env:
        GITHUB_TOKEN: ${{ github.token }}